# ---------------------------------------------------------------------------------------------
# Copyright (C) ygguser 2023.
# https://github.com/ygguser
#
# Distributed under the MIT License (license terms are at http://opensource.org/licenses/MIT).
# ---------------------------------------------------------------------------------------------

name: Build & Release (test)

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  get_version:
    name: Get version from Cargo.toml
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ env.VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Getting version
        run: echo "VERSION=$(sed -nE 's/^version\s*=\s*(\S*)$/\1/p' Cargo.toml | tr -d '\"')" >> $GITHUB_ENV
        
  build_and_upload_drwn:
      name: Create and upload binaries (darwin)
      runs-on: macos-12
      strategy:
        matrix:
          target: [ x86_64-apple-darwin ]
      steps:
      - name: Checkout code
        uses: actions/checkout@v3    
      
      - name: Preparing for cross-compilation (darwin)
        run: |
          rustup update
          rustup target add x86_64-apple-darwin
          #rustup target add x86_64h-apple-darwin
          #rustup +nightly component add rust-src
          #cargo +nightly build -Z build-std --target x86_64h-apple-darwin
   
      - name: Build and compress binaries (darwin)
        if: ${{contains(matrix.target, 'darwin')}}
        run: |
         #.github/workflows/build+zip_drwn2.sh ${{ matrix.target }} 
         cargo build --release --target x86_64-apple-darwin
         chmod og+x "target/x86_64-apple-darwin/release/peers_updater"
         zip -9 -j "target/x86_64-apple-darwin/release/x86_64-apple-darwin.zip" "target/x86_64-apple-darwin/release/peers_updater"   

  build_and_upload:
    name: Create and upload binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ i686-unknown-linux-gnu, aarch64-unknown-linux-gnu, x86_64-unknown-linux-gnu, arm-unknown-linux-gnueabi, i686-pc-windows-gnu, x86_64-pc-windows-gnu, armv7-unknown-linux-gnueabihf ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Preparing for cross-compilation (arm)
        if: ${{contains(matrix.target, 'armv7-unknown-linux-gnueabihf') || contains(matrix.target, 'arm-unknown-linux-gnueabi')}}
        run: |
          sudo apt update && sudo DEBIAN_FRONTEND='noninteractive' apt-get -y -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold' upgrade && sudo apt-get -y install zip upx gcc-arm-linux-gnueabihf
          rustup update
          #rustup component add rust-src
          #rustup toolchain install nightly
          #rustup component add rust-src --toolchain nightly
          cargo install --force --locked cross
          #rustup toolchain install nightly-2023-02-15-x86_64-unknown-linux-gnu
          #rustup component add rust-src --toolchain nightly-2023-02-15-x86_64-unknown-linux-gnu
          #mv ~/.rustup/toolchains/nightly-2023-02-15-x86_64-unknown-linux-gnu ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu

      - name: Preparing for cross-compilation (other)         
        if: ${{!contains(matrix.target, 'arm') && !contains(matrix.target, 'darwin')}}
        run: |
          sudo apt update && sudo DEBIAN_FRONTEND='noninteractive' apt-get -y -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold' upgrade && sudo apt-get -y install zip upx gcc-aarch64-linux-gnu
          rustup update
          #rustup component add rust-src
          #rustup toolchain install nightly
          #rustup component add rust-src --toolchain nightly
          cargo install --force --locked cross
          #rustup toolchain install nightly-2023-02-15-x86_64-unknown-linux-gnu
          #rustup component add rust-src --toolchain nightly-2023-02-15-x86_64-unknown-linux-gnu
          #mv ~/.rustup/toolchains/nightly-2023-02-15-x86_64-unknown-linux-gnu ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu  
          
      - name: Build and compress binaries (other)
        if: ${{!contains(matrix.target, 'darwin')}}
        run: .github/workflows/build+zip.sh ${{ matrix.target }}        

