name: Draft a new release

on:
  push:
    #tags: v[0-9].[0-9]+.[0-9]+
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  get_version:
    name: Get version from Cargo.toml
    runs-on: ubuntu-latest
    outputs:
      project_version: ${{ env.VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Getting version
        #run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        run: sed -nE 's/^version\s*=\s*(\S*)$/\1/p' Cargo.toml  | tr -d '"' >> $GITHUB_ENV
        
  build:
    name: Create release
    runs-on: ubuntu-latest
    needs: get_version
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Peers updater v. {{ env.VERSION }}
          draft: true
          prerelease: false
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
